subscriptions/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'subscriptions.views.index', name='subscription'),
    url(r'^update$', 'subscriptions.views.update', name='subscription_update'),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

from mezzanine.core.views import direct_to_template

admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

ACCOUNT_URL = getattr(settings, "ACCOUNT_URL", "/account/")
SIGNUP_URL = getattr(settings, "SIGNUP_URL",
                     "/%s/signup/" % ACCOUNT_URL.strip("/"))
_slash = "/" if settings.APPEND_SLASH else ""

urlpatterns = patterns("",

    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),

    ("^orders/", include('orders.urls')),
    ("^subscription/", include('subscriptions.urls')),
    ("^account/", include('customers.urls')),
    ("^rewards/", include('rewards.urls')),
    ("^gifts/", include('gifts.urls')),

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    #url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

if settings.DEBUG:
    urlpatterns += patterns('',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        )
    )

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

gifts/models.py
from django.db import models
from promotions.models import Code


class GiftSubscription(models.Model):
    gifter = models.EmailField(max_length=254)
    giftee = models.EmailField(max_length=254)
    plan = models.ForeignKey('subscriptions.Plan')
    code = models.ForeignKey('promotions.Code')
    redeemed = models.DateTimeField(null=True, default=None)

    def save(self, *args, **kwargs):
        try:
            self.code
        except Code.DoesNotExist:
            code = Code()
            code.save()
            self.code = code

        super(GiftSubscription, self).save(*args, **kwargs)

subscriptions/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone
import stripe
from base.models import StripeObject


class LocationFullException(Exception):
    pass


def convert_tstamp(response, field_name=None):
    if response is not None:
        try:
            if field_name and response[field_name]:
                return datetime.fromtimestamp(
                    response[field_name],
                    timezone.utc
                )
            if not field_name:
                return datetime.fromtimestamp(
                    response,
                    timezone.utc
                )
        except KeyError:
            pass
    return None


class PlanManager(models.Manager):

    # Used for calculating prices using javascript in the subscription form
    def jsonify_for_form(self):
        plans = {}
        for plan in self.all():
            amount = plan.amount
            interval = plan.interval
            price = plan.price

            if not plans.get(amount):
                plans[amount] = {}

            if not plans[amount].get(interval):
                plans[amount][interval] = {}

            plans[amount][interval] = price

        return plans


class Plan(StripeObject):
    amount = models.FloatField() # pounds
    price = models.DecimalField(decimal_places=2, max_digits=7)
    public = models.BooleanField(default=True)
    interval = models.IntegerField() # months
    trial = models.BooleanField(default=False)

    objects = PlanManager()

    class Meta:
        unique_together = ('amount', 'price', 'interval', 'trial')

    def __unicode__(self):

        trial = ''
        if self.trial:
            trial = ' with trial'

        return '{amount_str} for {interval_str} at ${price:,.2f}{trial}'\
            .format(
                amount_str=self.amount_str,
                interval_str=self.interval_str,
                price=self.price,
                trial=trial)

    def save(self, *args, **kwargs):

        # dynamic default for stripe_id
        self.stripe_id = str(self)

        # sync with stripe
        try:
            stripe.Plan.retrieve(str(self))
        except stripe.InvalidRequestError:
            trial_period_days = None
            if self.trial:
                trial_period_days = '14'
            stripe.Plan.create(
                amount=int(100 * self.price),
                interval = 'month',
                interval_count=self.interval,
                name=str(self),
                currency='usd',
                id=self.stripe_id,
                trial_period_days=trial_period_days)

        super(Plan, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        plan = stripe.Plan.retrieve(self.stripe_id)
        plan.delete()
        super(Plan, self).save(*args, **kwargs)

    @property
    def amount_str(self):
        if self.amount < 1:
            amount = self.amount * 16
            unit = 'ozs'
        else:
            amount = self.amount
            unit = 'lbs'

        if amount == 1:
            unit = unit.rstrip('s')

        return '{amount:g} {unit}'.format(**locals())

    @property
    def interval_str(self):
        interval = self.interval
        unit = 'months'

        if interval == 1:
            unit = unit.rstrip('s')

        return '{interval:g} {unit}'.format(**locals())


class Subscription(models.Model):
    customer = models.OneToOneField('customers.Customer', related_name="_subscription")
    plan = models.ForeignKey('subscriptions.Plan', related_name='subscriptions')

    # Stripe supports all status except paused. Store here so stripe sync
    # doesn't overwrite a paused status and use a status property to return
    # the true status
    paused = models.BooleanField(default=False)

    # stripe fields
    started = models.DateTimeField()
    # TODO: Migrate this to "Cancelled"
    canceled = models.DateTimeField(null=True)
    ended = models.DateTimeField(null=True)
    current_period_start = models.DateTimeField(null=True)
    current_period_end = models.DateTimeField(null=True)
    # trialing, active, past_due, canceled, or unpaid
    stripe_status = models.CharField(max_length=25)

    def __unicode__(self):
        return '%s - %s' % (self.customer, self.plan)

    def save(self, coupon=None, *args, **kwargs):

        # sync with stripe, this can override every field but customer
        sc = self.customer.stripe_customer
        sc.update_subscription(plan=self.plan.stripe_id, coupon=coupon)
        stripe_sub = sc.subscription

        if stripe_sub:
            self.plan = Plan.objects.get(stripe_id=stripe_sub.plan.id)
            self.current_period_start = convert_tstamp(stripe_sub.current_period_start)
            self.current_period_end = convert_tstamp(stripe_sub.current_period_end)
            self.stripe_status = stripe_sub.status
            self.started = convert_tstamp(stripe_sub.start)
            self.canceled = convert_tstamp(stripe_sub.canceled_at)

        # make sure location is not full
        #if self.location.capacity_remaining < self.plan.amount:
        #    raise LocationFullException

        super(Subscription, self).save(*args, **kwargs)

    def cancel(self):
        #TODO: potential double-click problem / race condition
        if self.customer.stripe_customer.subscription:
            self.customer.stripe_customer.cancel_subscription()
            self.canceled = datetime.utcnow().replace(tzinfo=timezone.utc)
            self.save()

    @property
    def status(self):
        if self.paused:
            return 'paused'
        return self.stripe_status

    @property
    def period_is_current(self):
        return self.current_period_end > \
            datetime.utcnow().replace(tzinfo=timezone.utc)

    @property
    def status_is_current(self):
        return self.status in ["trialing", "active"]

    @property
    def active(self):
        return self.period_is_current and self.status_is_current

    def pause(self):
        self.paused = True
        self.save()

    def unpause(self):
        self.paused = False
        self.save()

subscriptions/forms.py
from django import forms
from subscriptions.models import Plan, Subscription


PLAN_AMOUNT_CHOICES = (
    (0.125, '2oz Trial'),
    (0.5, '8oz'),
    (0.75, '12oz'),
    (1.0, '16oz'),
)

PLAN_AMOUNT_CHOICES_UPDATE = (
    (0.5, '8oz'),
    (0.75, '12oz'),
    (1.0, '16oz'),
)

PLAN_INTERVAL_CHOICES = (
    (1, 'Monthly'),
    (3, '3 months'),
    (12, '1 year'),
)

class SubscriptionForm(forms.Form):

    amount = forms.ChoiceField(
        widget=forms.widgets.RadioSelect,
        choices=PLAN_AMOUNT_CHOICES)
    interval = forms.ChoiceField(
        widget=forms.widgets.RadioSelect,
        choices=PLAN_INTERVAL_CHOICES, required=False)

    def clean_interval(self):
        interval = self.cleaned_data['interval']
        if self.cleaned_data.get('amount') == '0.125':
            if interval:
                raise forms.ValidationError('No interval should be selected for the trial amount')
            else:
                return interval
        else:
            if not interval:
                raise forms.ValidationError('Interval is required')
            else:
                return interval


class SubscriptionUpdateForm(forms.Form):

    amount = forms.ChoiceField(
        widget=forms.widgets.RadioSelect,
        choices=PLAN_AMOUNT_CHOICES_UPDATE)
    interval = forms.ChoiceField(
        widget=forms.widgets.RadioSelect,
        choices=PLAN_INTERVAL_CHOICES)

subscriptions/views.py
from annoying.decorators import render_to
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from subscriptions.forms import SubscriptionUpdateForm
from subscriptions.models import Plan, Subscription

@login_required
@render_to('subscriptions/index.html')
def index(request):

    customer = request.user.customer

    try:
        subscription = customer.subscription
    except Subscription.DoesNotExist:
        subscription = None

    msg = ''

    if request.method == 'POST' and subscription:
        action = request.POST.get('action')
        if action == 'pause':
            subscription.pause()
        if action == 'unpause':
            subscription.unpause()
        #TODO
        #elif action == 'cancel':
        #    subscription.cancel()
        elif action == 'change':
            return HttpResponseRedirect(reverse('subscriptions.views.update'))

    return locals()


@login_required
@render_to('subscriptions/update.html')
def update(request):

    customer = request.user.customer
    plans = Plan.objects.jsonify_for_form()
    data_key = settings.STRIPE_PUBLIC_KEY

    subscription_form = None
    if request.method == 'POST':
        subscription_form = SubscriptionUpdateForm(request.POST)
        if subscription_form.is_valid():
            plan = Plan.objects.get(
                amount=subscription_form.cleaned_data['amount'],
                interval=subscription_form.cleaned_data['interval'])
            customer.update_card(request.POST.get('stripeToken'))
            customer.subscription.plan = plan
            customer.subscription.save()
            # This fixes the bug where, when the form was submitted, the values
            # were unicode strings instead of ints and radio checking in the
            # template would not work because of type mismatch
            subscription_form = None

    if not subscription_form:
        subscription = customer.subscription
        subscription_form = SubscriptionUpdateForm({
            'amount':subscription.plan.amount,
            'interval':subscription.plan.interval})

    return locals()

subscriptions/templates/subscriptions/form.html
{% load jsonify %}

<script type="text/javascript">

// Turn interval and amount radios into jquery buttonsets
$(function() {
  $('#amount_radios').buttonset();
  $('#interval_radios').buttonset();
});

// Update the grand total HTML with a given price or calculate based on
// chosen interval and amount
function update_total(price) {
  if (!price) {
    var plans = {{plans|jsonify}};
    var amount = $('input:checked[name="amount"]').val();
    if (!amount) {
      price = 'Select an amount';
    } else {
      var interval = $('input:checked[name="interval"]').val();
      if (!interval) {
        price = 'Select an interval';
      } else {
        price = plans[amount][interval];
        price = '$' + price.toString();
      }
    }
  }
  $('#signup_total').html('Grand Total: ' + price);
}

// Event handling code for interval/amount buttons
$(function(){
  $("input[type='radio']").change(function(obj) {

    //disable interval when choosing the 2oz trial or re-enable when deselected
    if ($('input:checked[name="amount"]').val() == 0.125) {
      $('input[name="interval"]').button({disabled:true});
      $('input[name="interval"]').prop('checked', false);
      $('#interval_radios').buttonset('refresh');
      update_total('Free!');
    } else {
      $('input[name="interval"]').button({disabled:false});
      update_total();
    }
  });
});

// Initialize total
$(function(){
  update_total();
});

// Make an ajax request to see if the code is valid and apply it if so
function apply_code() {
  var code = $('#id_code').val();
  var email = $('#id_email').val();
  $.ajax({
    url: '{{code_check_url}}',
    data: {
      'code': code,
      'email': email
    },
  }).done(function(data) {
    data = JSON.parse(data);
    if (data) {
      // Update interval and amount radios
      var input = "input[type='radio']";
      var interval = "[name='interval'][value='" + data['interval'] + "']";
      var amount = "[name='amount'][value='" + data['amount'] + "']";

      // Disable all buttons
      $("input[type='radio']").button({disabled:true});

      // Just enable the amount and interval gifted
      $(input + interval).button({disabled:false});
      $(input + amount).button({disabled:false});

      // Actual click the radios of the amount and interval gifted
      $(input + interval).attr("checked", "checked").button('refresh');
      $(input + amount).attr("checked", "checked").button('refresh');

      // Don't allow other 'on change' code to mess with button state
      $('input[type="radio"]').unbind('change');

      // Update grand total
      update_total('Free!');

      // Remove stripe button
      $('.stripe-button-el').remove();

      // Place redeem code button
      $('#redeem_code_btn').show();

      // Remove invalid code msg if present
      $('.input_id_code .help-inline').html('');

      // Get rid of "Is this a gift?"
      $('#gift_checkbox').hide();
      $('label[for="gift_checkbox"]').hide();
    } else {
      $('.input_id_code .help-inline').html('Invalid code!');
    }
  });

}

$(function(){
  // Handle gift code application
  $("#apply_code_btn").click(function(obj) { apply_code(); });

  // Apply code on page load if filled in
  if ($('#id_code').val()) { apply_code(); }
});
</script>

<div class="control-group input_id_plan">
<div class="center">
  <div id="amount_radios">
    {% for value, text in subscription_form.fields.amount.choices %}
    <input {% if subscription_form.amount.value == value %}checked="checked"{%endif%} id="amount_{{value}}" type="radio" value="{{value}}" name="amount"/>
    <label for="amount_{{value}}">{{text}}</label>
    {% endfor %}
  </div>
  <p class="content">
  How long do you want your subscription to last?
  </p>
  <div class="center">
    <div id="interval_radios">
    {% for value, text in subscription_form.fields.interval.choices %}
      <input {% if subscription_form.interval.value == value %}checked="checked"{%endif%} id="interval_{{value}}" type="radio" value="{{value}}" name="interval"/>
      <label for="interval_{{value}}">{{text}}</label>
    {% endfor %}
    </div>
  </div>
  <p class="content">
  *Please note that 3 month and 1 year subscriptions will only be cancelled after the subscription period has elapsed!*
  </p>
  </div>

<div class="control-group input_id_code">
    <label for="id_code" class="signup">Have a gift/promo code?</label>
    <div class="controls">
        <input id="id_code" name="code" type="text" />
        <span class="help-inline"></span>
        <input type="button" class="btn" id="apply_code_btn" value="Apply Code"></input>
    </div>
</div>

{% for field in reward_code_form %}
  <div class="control-group input_{{ field.id_for_label }} {{ field.field.type }}
    {% if field.errors %} error{% endif %}">
    {{ field.label_tag }}
    <div class="controls">
      {{ field }}
      {% if field.errors %}
      <span class="help-inline">
        {% for e in field.errors %}
        {% if not forloop.first %} / {% endif %}{{ e }}
        {% endfor %}
      </span>
      {% else %}
      <span class="help-inline">{{ field.help_text }}</span>
      {% endif %}
    </div>
  </div>
{% endfor %}

<h3 id="signup_total">Grand Total:</h3>
<input type="submit" class="btn" id="redeem_code_btn" value="Redeem Gift" style="display:none"></input>
<script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button" data-key="{{stripe_key}}">
</script>

subscriptions/templates/subscriptions/index.html
{% extends "customers/home.html" %}

{% block main %}


<div class="loggedin">
<div class="invitewrap">

<h2>Subscription</h2>

<p class="shadow">
{% if subscription.active %}
Awesome, you have an active subscription!
{% elif subscription.paused %}
Your subscription is currently paused.
{% endif %}
<br/><br/>
Current subscription size: {{ subscription.plan.amount_str }}
<br/><br/>
Current subscription length: {{ subscription.plan.interval_str }}
<br/><br/>
What would you like to do?
<br/>

<form method="post">
{% csrf_token %}

{% if subscription.active %}
<button class="btn" name="action" value="pause">Pause Subscription</button>
{% elif subscription.paused %}
<button class="btn" name="action" value="unpause">Unpause Subscription</button>
{% endif %}
<br /><br />
{# <button class="btn" name="action" value="change">Change Subscription</button> #}
</form>

</div>
</div>

{% endblock %}

subscriptions/templates/subscriptions/update.html
{% extends "customers/home.html" %}

{% block main %}
<div class="loggedin">
<form class="update" method="post">
{% csrf_token %}
  <h2>Update your subscription</h2>
  {% include "subscriptions/form.html" %}
</form>
</div>
{% endblock %}